root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/goigniter"
  cmd = "go build -o tmp/goigniter ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "storage", "agents"]
  exclude_file = []
  exclude_regex = [".*_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "env"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun_delay = 500
  rerun_on_error = false
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "green"
  runner = "cyan"
  watcher = "blue"

[log]
  main_only = false
  time = false
